version: '3'

services:

  reverse-proxy: # this is service name
    image: nginx:1.17.10 # pulling this image from registry
    container_name: reverse_proxy # giving name to this container
    depends_on: # services it will be able to talk to
        - frontend-service 
        - timetable-service
    volumes:
      - ./image_sources/nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports: # port of local machine mapped to port of exposed port of container
      - 80:80

  frontend-service: # this is service name
    image: frontend-service # name given to the image
    container_name: frontend_service # giving name to this container
    build:
      context: ./image_sources/frontend_service # building from docker file in this directory
    depends_on:
        - timetable-service
    ports: # port of local machine mapped to port of exposed port of container
      - 8080:80
    restart: on-failure


  timetable-service:
    image: timetable-service # name given to the image
    container_name: timetable_service # giving name to this container
    build:
      context: ./image_sources/timetable_service # building from docker file in this directory
    ports: # port of local machine mapped to port of exposed port of container
      - 5001:5001
    restart: on-failure


  mongodb:
    container_name: mongodb # name being given to its container 
    image: mongo # image pulled from docker hub instead of building your own from docker file
    ports:
      - '27018:27017' # port of local machine
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
    driver: local