apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    # obtained from echo -n 'your_username' | base64
    mongo-root-password: cGFzc3dvcmQ=
    # obtained from echo -n 'your_password' | base64