runtime: nodejs14 # or another supported version

instance_class: F2

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# this file is added for adding the app to google compute engine